# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ChatPrototypes.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ChatPrototypes.proto',
  package='message',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x43hatPrototypes.proto\x12\x07message\"A\n\x0b\x43hatMessage\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\t\"\xb4\x01\n\x06Topics\x12\"\n\nchat_topic\x18\x01 \x01(\t:\x0e/chat/messages\x12\"\n\x0csystem_topic\x18\x02 \x01(\t:\x0c/chat/system\x12\x32\n\x14system_request_topic\x18\x03 \x01(\t:\x14/chat/system/request\x12.\n\x15system_response_topic\x18\x04 \x01(\t:\x0f/chat/response/\"\x95\x02\n\x0eSystemMessages\x12!\n\x0e\x63onnected_text\x18\x01 \x01(\t:\tconnected\x12\'\n\x11\x64isconnected_text\x18\x02 \x01(\t:\x0c\x64isconnected\x12&\n\x0bjoined_text\x18\x03 \x01(\t:\x11Joined group chat\x12*\n\x12\x61\x63\x63\x65ss_denied_text\x18\x04 \x01(\t:\x0e\x41\x63\x63\x65ss denied!\x12\'\n\x11request_join_text\x18\x05 \x01(\t:\x0cJoin request\x12\x1e\n\x11\x61pprove_join_text\x18\x06 \x01(\t:\x03yes\x12\x1a\n\x0e\x64\x65ny_join_text\x18\x07 \x01(\t:\x02no'
)




_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='message.ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sender', full_name='message.ChatMessage.sender', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='message.ChatMessage.content', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='message.ChatMessage.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=98,
)


_TOPICS = _descriptor.Descriptor(
  name='Topics',
  full_name='message.Topics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_topic', full_name='message.Topics.chat_topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/messages".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_topic', full_name='message.Topics.system_topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/system".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_request_topic', full_name='message.Topics.system_request_topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/system/request".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_response_topic', full_name='message.Topics.system_response_topic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/response/".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=281,
)


_SYSTEMMESSAGES = _descriptor.Descriptor(
  name='SystemMessages',
  full_name='message.SystemMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connected_text', full_name='message.SystemMessages.connected_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"connected".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnected_text', full_name='message.SystemMessages.disconnected_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"disconnected".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joined_text', full_name='message.SystemMessages.joined_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Joined group chat".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_denied_text', full_name='message.SystemMessages.access_denied_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Access denied!".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_join_text', full_name='message.SystemMessages.request_join_text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Join request".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='approve_join_text', full_name='message.SystemMessages.approve_join_text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"yes".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deny_join_text', full_name='message.SystemMessages.deny_join_text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"no".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=561,
)

DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['Topics'] = _TOPICS
DESCRIPTOR.message_types_by_name['SystemMessages'] = _SYSTEMMESSAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), {
  'DESCRIPTOR' : _CHATMESSAGE,
  '__module__' : 'ChatPrototypes_pb2'
  # @@protoc_insertion_point(class_scope:message.ChatMessage)
  })
_sym_db.RegisterMessage(ChatMessage)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), {
  'DESCRIPTOR' : _TOPICS,
  '__module__' : 'ChatPrototypes_pb2'
  # @@protoc_insertion_point(class_scope:message.Topics)
  })
_sym_db.RegisterMessage(Topics)

SystemMessages = _reflection.GeneratedProtocolMessageType('SystemMessages', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMMESSAGES,
  '__module__' : 'ChatPrototypes_pb2'
  # @@protoc_insertion_point(class_scope:message.SystemMessages)
  })
_sym_db.RegisterMessage(SystemMessages)


# @@protoc_insertion_point(module_scope)
