# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: system_messages.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='system_messages.proto',
  package='system_messages',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15system_messages.proto\x12\x0fsystem_messages\"\x95\x02\n\x0eSystemMessages\x12!\n\x0e\x63onnected_text\x18\x01 \x01(\t:\tconnected\x12\'\n\x11\x64isconnected_text\x18\x02 \x01(\t:\x0c\x64isconnected\x12&\n\x0bjoined_text\x18\x03 \x01(\t:\x11Joined group chat\x12*\n\x12\x61\x63\x63\x65ss_denied_text\x18\x04 \x01(\t:\x0e\x41\x63\x63\x65ss denied!\x12\'\n\x11request_join_text\x18\x05 \x01(\t:\x0cJoin request\x12\x1e\n\x11\x61pprove_join_text\x18\x06 \x01(\t:\x03yes\x12\x1a\n\x0e\x64\x65ny_join_text\x18\x07 \x01(\t:\x02no'
)




_SYSTEMMESSAGES = _descriptor.Descriptor(
  name='SystemMessages',
  full_name='system_messages.SystemMessages',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='connected_text', full_name='system_messages.SystemMessages.connected_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"connected".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnected_text', full_name='system_messages.SystemMessages.disconnected_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"disconnected".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='joined_text', full_name='system_messages.SystemMessages.joined_text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Joined group chat".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='access_denied_text', full_name='system_messages.SystemMessages.access_denied_text', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Access denied!".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_join_text', full_name='system_messages.SystemMessages.request_join_text', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"Join request".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='approve_join_text', full_name='system_messages.SystemMessages.approve_join_text', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"yes".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deny_join_text', full_name='system_messages.SystemMessages.deny_join_text', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"no".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=320,
)

DESCRIPTOR.message_types_by_name['SystemMessages'] = _SYSTEMMESSAGES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemMessages = _reflection.GeneratedProtocolMessageType('SystemMessages', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMMESSAGES,
  '__module__' : 'system_messages_pb2'
  # @@protoc_insertion_point(class_scope:system_messages.SystemMessages)
  })
_sym_db.RegisterMessage(SystemMessages)


# @@protoc_insertion_point(module_scope)
