#!/bin/bash
  
PROTO_EXECUTABLE_DIR="$1"
PROTO_SRC_DIR="./"
PROTO_SRC_NAME="ChatPrototypes.proto"
PROTO_DEST_JAVA="Java-Application/src/main/java/"
PROTO_DEST_PYTHON="MQTT_Chat_Library/mqtt_chat_library/"

if [ $# -eq 2 ]
        
then
	for filename in PROTO_SRC_DIR;
		do
			$($PROTO_EXECUTABLE_DIR"protoc" --proto_path=$PROTO_SRC_DIR --java_out=$PROTO_DEST_JAVA "$PROTO_SRC_DIR$filename")
			$($PROTO_EXECUTABLE_DIR"protoc" --proto_path=$PROTO_SRC_DIR --python_out=$PROTO_DEST_PYTHON "$PROTO_SRC_DIR$filename")
	done
else    
	for filename in PROTO_SRC_DIR;
		do
			$(protoc --proto_path=$PROTO_SRC_DIR --java_out=$PROTO_DEST_JAVA "$PROTO_SRC_DIR$filename")
			$(protoc --proto_path=$PROTO_SRC_DIR --python_out=$PROTO_DEST_PYTHON "$PROTO_SRC_DIR$filename")
	done       
fi