# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: topics.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='topics.proto',
  package='chat_topics',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0ctopics.proto\x12\x0b\x63hat_topics\"\xb4\x01\n\x06Topics\x12\"\n\nchat_topic\x18\x01 \x01(\t:\x0e/chat/messages\x12\"\n\x0csystem_topic\x18\x02 \x01(\t:\x0c/chat/system\x12\x32\n\x14system_request_topic\x18\x03 \x01(\t:\x14/chat/system/request\x12.\n\x15system_response_topic\x18\x04 \x01(\t:\x0f/chat/response/'
)




_TOPICS = _descriptor.Descriptor(
  name='Topics',
  full_name='chat_topics.Topics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='chat_topic', full_name='chat_topics.Topics.chat_topic', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/messages".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_topic', full_name='chat_topics.Topics.system_topic', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/system".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_request_topic', full_name='chat_topics.Topics.system_request_topic', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/system/request".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='system_response_topic', full_name='chat_topics.Topics.system_response_topic', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=b"/chat/response/".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=210,
)

DESCRIPTOR.message_types_by_name['Topics'] = _TOPICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Topics = _reflection.GeneratedProtocolMessageType('Topics', (_message.Message,), {
  'DESCRIPTOR' : _TOPICS,
  '__module__' : 'topics_pb2'
  # @@protoc_insertion_point(class_scope:chat_topics.Topics)
  })
_sym_db.RegisterMessage(Topics)


# @@protoc_insertion_point(module_scope)
