// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: topics.proto

package chat_topics;

public final class TopicsOuterClass {
  private TopicsOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TopicsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:chat_topics.Topics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return Whether the chatTopic field is set.
     */
    boolean hasChatTopic();
    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return The chatTopic.
     */
    java.lang.String getChatTopic();
    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return The bytes for chatTopic.
     */
    com.google.protobuf.ByteString
        getChatTopicBytes();

    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return Whether the systemTopic field is set.
     */
    boolean hasSystemTopic();
    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return The systemTopic.
     */
    java.lang.String getSystemTopic();
    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return The bytes for systemTopic.
     */
    com.google.protobuf.ByteString
        getSystemTopicBytes();

    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return Whether the systemRequestTopic field is set.
     */
    boolean hasSystemRequestTopic();
    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return The systemRequestTopic.
     */
    java.lang.String getSystemRequestTopic();
    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return The bytes for systemRequestTopic.
     */
    com.google.protobuf.ByteString
        getSystemRequestTopicBytes();

    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return Whether the systemResponseTopic field is set.
     */
    boolean hasSystemResponseTopic();
    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return The systemResponseTopic.
     */
    java.lang.String getSystemResponseTopic();
    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return The bytes for systemResponseTopic.
     */
    com.google.protobuf.ByteString
        getSystemResponseTopicBytes();
  }
  /**
   * Protobuf type {@code chat_topics.Topics}
   */
  public static final class Topics extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:chat_topics.Topics)
      TopicsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Topics.newBuilder() to construct.
    private Topics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Topics() {
      chatTopic_ = "/chat/messages";
      systemTopic_ = "/chat/system";
      systemRequestTopic_ = "/chat/system/request";
      systemResponseTopic_ = "/chat/response/";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Topics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Topics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              chatTopic_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              systemTopic_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              systemRequestTopic_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              systemResponseTopic_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return chat_topics.TopicsOuterClass.internal_static_chat_topics_Topics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return chat_topics.TopicsOuterClass.internal_static_chat_topics_Topics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              chat_topics.TopicsOuterClass.Topics.class, chat_topics.TopicsOuterClass.Topics.Builder.class);
    }

    private int bitField0_;
    public static final int CHAT_TOPIC_FIELD_NUMBER = 1;
    private volatile java.lang.Object chatTopic_;
    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return Whether the chatTopic field is set.
     */
    @java.lang.Override
    public boolean hasChatTopic() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return The chatTopic.
     */
    @java.lang.Override
    public java.lang.String getChatTopic() {
      java.lang.Object ref = chatTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          chatTopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
     * @return The bytes for chatTopic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getChatTopicBytes() {
      java.lang.Object ref = chatTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        chatTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEM_TOPIC_FIELD_NUMBER = 2;
    private volatile java.lang.Object systemTopic_;
    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return Whether the systemTopic field is set.
     */
    @java.lang.Override
    public boolean hasSystemTopic() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return The systemTopic.
     */
    @java.lang.Override
    public java.lang.String getSystemTopic() {
      java.lang.Object ref = systemTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          systemTopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
     * @return The bytes for systemTopic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSystemTopicBytes() {
      java.lang.Object ref = systemTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEM_REQUEST_TOPIC_FIELD_NUMBER = 3;
    private volatile java.lang.Object systemRequestTopic_;
    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return Whether the systemRequestTopic field is set.
     */
    @java.lang.Override
    public boolean hasSystemRequestTopic() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return The systemRequestTopic.
     */
    @java.lang.Override
    public java.lang.String getSystemRequestTopic() {
      java.lang.Object ref = systemRequestTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          systemRequestTopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
     * @return The bytes for systemRequestTopic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSystemRequestTopicBytes() {
      java.lang.Object ref = systemRequestTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemRequestTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SYSTEM_RESPONSE_TOPIC_FIELD_NUMBER = 4;
    private volatile java.lang.Object systemResponseTopic_;
    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return Whether the systemResponseTopic field is set.
     */
    @java.lang.Override
    public boolean hasSystemResponseTopic() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return The systemResponseTopic.
     */
    @java.lang.Override
    public java.lang.String getSystemResponseTopic() {
      java.lang.Object ref = systemResponseTopic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          systemResponseTopic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
     * @return The bytes for systemResponseTopic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSystemResponseTopicBytes() {
      java.lang.Object ref = systemResponseTopic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        systemResponseTopic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, chatTopic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, systemTopic_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, systemRequestTopic_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, systemResponseTopic_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, chatTopic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, systemTopic_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, systemRequestTopic_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, systemResponseTopic_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof chat_topics.TopicsOuterClass.Topics)) {
        return super.equals(obj);
      }
      chat_topics.TopicsOuterClass.Topics other = (chat_topics.TopicsOuterClass.Topics) obj;

      if (hasChatTopic() != other.hasChatTopic()) return false;
      if (hasChatTopic()) {
        if (!getChatTopic()
            .equals(other.getChatTopic())) return false;
      }
      if (hasSystemTopic() != other.hasSystemTopic()) return false;
      if (hasSystemTopic()) {
        if (!getSystemTopic()
            .equals(other.getSystemTopic())) return false;
      }
      if (hasSystemRequestTopic() != other.hasSystemRequestTopic()) return false;
      if (hasSystemRequestTopic()) {
        if (!getSystemRequestTopic()
            .equals(other.getSystemRequestTopic())) return false;
      }
      if (hasSystemResponseTopic() != other.hasSystemResponseTopic()) return false;
      if (hasSystemResponseTopic()) {
        if (!getSystemResponseTopic()
            .equals(other.getSystemResponseTopic())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasChatTopic()) {
        hash = (37 * hash) + CHAT_TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getChatTopic().hashCode();
      }
      if (hasSystemTopic()) {
        hash = (37 * hash) + SYSTEM_TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getSystemTopic().hashCode();
      }
      if (hasSystemRequestTopic()) {
        hash = (37 * hash) + SYSTEM_REQUEST_TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getSystemRequestTopic().hashCode();
      }
      if (hasSystemResponseTopic()) {
        hash = (37 * hash) + SYSTEM_RESPONSE_TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getSystemResponseTopic().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static chat_topics.TopicsOuterClass.Topics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static chat_topics.TopicsOuterClass.Topics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static chat_topics.TopicsOuterClass.Topics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(chat_topics.TopicsOuterClass.Topics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code chat_topics.Topics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:chat_topics.Topics)
        chat_topics.TopicsOuterClass.TopicsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return chat_topics.TopicsOuterClass.internal_static_chat_topics_Topics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return chat_topics.TopicsOuterClass.internal_static_chat_topics_Topics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                chat_topics.TopicsOuterClass.Topics.class, chat_topics.TopicsOuterClass.Topics.Builder.class);
      }

      // Construct using chat_topics.TopicsOuterClass.Topics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        chatTopic_ = "/chat/messages";
        bitField0_ = (bitField0_ & ~0x00000001);
        systemTopic_ = "/chat/system";
        bitField0_ = (bitField0_ & ~0x00000002);
        systemRequestTopic_ = "/chat/system/request";
        bitField0_ = (bitField0_ & ~0x00000004);
        systemResponseTopic_ = "/chat/response/";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return chat_topics.TopicsOuterClass.internal_static_chat_topics_Topics_descriptor;
      }

      @java.lang.Override
      public chat_topics.TopicsOuterClass.Topics getDefaultInstanceForType() {
        return chat_topics.TopicsOuterClass.Topics.getDefaultInstance();
      }

      @java.lang.Override
      public chat_topics.TopicsOuterClass.Topics build() {
        chat_topics.TopicsOuterClass.Topics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public chat_topics.TopicsOuterClass.Topics buildPartial() {
        chat_topics.TopicsOuterClass.Topics result = new chat_topics.TopicsOuterClass.Topics(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.chatTopic_ = chatTopic_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.systemTopic_ = systemTopic_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.systemRequestTopic_ = systemRequestTopic_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.systemResponseTopic_ = systemResponseTopic_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof chat_topics.TopicsOuterClass.Topics) {
          return mergeFrom((chat_topics.TopicsOuterClass.Topics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(chat_topics.TopicsOuterClass.Topics other) {
        if (other == chat_topics.TopicsOuterClass.Topics.getDefaultInstance()) return this;
        if (other.hasChatTopic()) {
          bitField0_ |= 0x00000001;
          chatTopic_ = other.chatTopic_;
          onChanged();
        }
        if (other.hasSystemTopic()) {
          bitField0_ |= 0x00000002;
          systemTopic_ = other.systemTopic_;
          onChanged();
        }
        if (other.hasSystemRequestTopic()) {
          bitField0_ |= 0x00000004;
          systemRequestTopic_ = other.systemRequestTopic_;
          onChanged();
        }
        if (other.hasSystemResponseTopic()) {
          bitField0_ |= 0x00000008;
          systemResponseTopic_ = other.systemResponseTopic_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        chat_topics.TopicsOuterClass.Topics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (chat_topics.TopicsOuterClass.Topics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object chatTopic_ = "/chat/messages";
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @return Whether the chatTopic field is set.
       */
      public boolean hasChatTopic() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @return The chatTopic.
       */
      public java.lang.String getChatTopic() {
        java.lang.Object ref = chatTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            chatTopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @return The bytes for chatTopic.
       */
      public com.google.protobuf.ByteString
          getChatTopicBytes() {
        java.lang.Object ref = chatTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          chatTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @param value The chatTopic to set.
       * @return This builder for chaining.
       */
      public Builder setChatTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        chatTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @return This builder for chaining.
       */
      public Builder clearChatTopic() {
        bitField0_ = (bitField0_ & ~0x00000001);
        chatTopic_ = getDefaultInstance().getChatTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string chat_topic = 1 [default = "/chat/messages"];</code>
       * @param value The bytes for chatTopic to set.
       * @return This builder for chaining.
       */
      public Builder setChatTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        chatTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object systemTopic_ = "/chat/system";
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @return Whether the systemTopic field is set.
       */
      public boolean hasSystemTopic() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @return The systemTopic.
       */
      public java.lang.String getSystemTopic() {
        java.lang.Object ref = systemTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            systemTopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @return The bytes for systemTopic.
       */
      public com.google.protobuf.ByteString
          getSystemTopicBytes() {
        java.lang.Object ref = systemTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @param value The systemTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        systemTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSystemTopic() {
        bitField0_ = (bitField0_ & ~0x00000002);
        systemTopic_ = getDefaultInstance().getSystemTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_topic = 2 [default = "/chat/system"];</code>
       * @param value The bytes for systemTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        systemTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object systemRequestTopic_ = "/chat/system/request";
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @return Whether the systemRequestTopic field is set.
       */
      public boolean hasSystemRequestTopic() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @return The systemRequestTopic.
       */
      public java.lang.String getSystemRequestTopic() {
        java.lang.Object ref = systemRequestTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            systemRequestTopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @return The bytes for systemRequestTopic.
       */
      public com.google.protobuf.ByteString
          getSystemRequestTopicBytes() {
        java.lang.Object ref = systemRequestTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemRequestTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @param value The systemRequestTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemRequestTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        systemRequestTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSystemRequestTopic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        systemRequestTopic_ = getDefaultInstance().getSystemRequestTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_request_topic = 3 [default = "/chat/system/request"];</code>
       * @param value The bytes for systemRequestTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemRequestTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        systemRequestTopic_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object systemResponseTopic_ = "/chat/response/";
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @return Whether the systemResponseTopic field is set.
       */
      public boolean hasSystemResponseTopic() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @return The systemResponseTopic.
       */
      public java.lang.String getSystemResponseTopic() {
        java.lang.Object ref = systemResponseTopic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            systemResponseTopic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @return The bytes for systemResponseTopic.
       */
      public com.google.protobuf.ByteString
          getSystemResponseTopicBytes() {
        java.lang.Object ref = systemResponseTopic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          systemResponseTopic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @param value The systemResponseTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemResponseTopic(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        systemResponseTopic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @return This builder for chaining.
       */
      public Builder clearSystemResponseTopic() {
        bitField0_ = (bitField0_ & ~0x00000008);
        systemResponseTopic_ = getDefaultInstance().getSystemResponseTopic();
        onChanged();
        return this;
      }
      /**
       * <code>optional string system_response_topic = 4 [default = "/chat/response/"];</code>
       * @param value The bytes for systemResponseTopic to set.
       * @return This builder for chaining.
       */
      public Builder setSystemResponseTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        systemResponseTopic_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:chat_topics.Topics)
    }

    // @@protoc_insertion_point(class_scope:chat_topics.Topics)
    private static final chat_topics.TopicsOuterClass.Topics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new chat_topics.TopicsOuterClass.Topics();
    }

    public static chat_topics.TopicsOuterClass.Topics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Topics>
        PARSER = new com.google.protobuf.AbstractParser<Topics>() {
      @java.lang.Override
      public Topics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Topics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Topics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Topics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public chat_topics.TopicsOuterClass.Topics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_topics_Topics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_topics_Topics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014topics.proto\022\013chat_topics\"\264\001\n\006Topics\022\"" +
      "\n\nchat_topic\030\001 \001(\t:\016/chat/messages\022\"\n\014sy" +
      "stem_topic\030\002 \001(\t:\014/chat/system\0222\n\024system" +
      "_request_topic\030\003 \001(\t:\024/chat/system/reque" +
      "st\022.\n\025system_response_topic\030\004 \001(\t:\017/chat" +
      "/response/"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chat_topics_Topics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_topics_Topics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_topics_Topics_descriptor,
        new java.lang.String[] { "ChatTopic", "SystemTopic", "SystemRequestTopic", "SystemResponseTopic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
