// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: system_messages.proto

package system_messages;

public final class SystemMessagesOuterClass {
  private SystemMessagesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SystemMessagesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:system_messages.SystemMessages)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return Whether the connectedText field is set.
     */
    boolean hasConnectedText();
    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return The connectedText.
     */
    java.lang.String getConnectedText();
    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return The bytes for connectedText.
     */
    com.google.protobuf.ByteString
        getConnectedTextBytes();

    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return Whether the disconnectedText field is set.
     */
    boolean hasDisconnectedText();
    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return The disconnectedText.
     */
    java.lang.String getDisconnectedText();
    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return The bytes for disconnectedText.
     */
    com.google.protobuf.ByteString
        getDisconnectedTextBytes();

    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return Whether the joinedText field is set.
     */
    boolean hasJoinedText();
    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return The joinedText.
     */
    java.lang.String getJoinedText();
    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return The bytes for joinedText.
     */
    com.google.protobuf.ByteString
        getJoinedTextBytes();

    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return Whether the accessDeniedText field is set.
     */
    boolean hasAccessDeniedText();
    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return The accessDeniedText.
     */
    java.lang.String getAccessDeniedText();
    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return The bytes for accessDeniedText.
     */
    com.google.protobuf.ByteString
        getAccessDeniedTextBytes();

    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return Whether the requestJoinText field is set.
     */
    boolean hasRequestJoinText();
    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return The requestJoinText.
     */
    java.lang.String getRequestJoinText();
    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return The bytes for requestJoinText.
     */
    com.google.protobuf.ByteString
        getRequestJoinTextBytes();

    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return Whether the approveJoinText field is set.
     */
    boolean hasApproveJoinText();
    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return The approveJoinText.
     */
    java.lang.String getApproveJoinText();
    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return The bytes for approveJoinText.
     */
    com.google.protobuf.ByteString
        getApproveJoinTextBytes();

    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return Whether the denyJoinText field is set.
     */
    boolean hasDenyJoinText();
    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return The denyJoinText.
     */
    java.lang.String getDenyJoinText();
    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return The bytes for denyJoinText.
     */
    com.google.protobuf.ByteString
        getDenyJoinTextBytes();
  }
  /**
   * Protobuf type {@code system_messages.SystemMessages}
   */
  public static final class SystemMessages extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:system_messages.SystemMessages)
      SystemMessagesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SystemMessages.newBuilder() to construct.
    private SystemMessages(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SystemMessages() {
      connectedText_ = "connected";
      disconnectedText_ = "disconnected";
      joinedText_ = "Joined group chat";
      accessDeniedText_ = "Access denied!";
      requestJoinText_ = "Join request";
      approveJoinText_ = "yes";
      denyJoinText_ = "no";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SystemMessages();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SystemMessages(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              connectedText_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              disconnectedText_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              joinedText_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              accessDeniedText_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              requestJoinText_ = bs;
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              approveJoinText_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000040;
              denyJoinText_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return system_messages.SystemMessagesOuterClass.internal_static_system_messages_SystemMessages_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return system_messages.SystemMessagesOuterClass.internal_static_system_messages_SystemMessages_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              system_messages.SystemMessagesOuterClass.SystemMessages.class, system_messages.SystemMessagesOuterClass.SystemMessages.Builder.class);
    }

    private int bitField0_;
    public static final int CONNECTED_TEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object connectedText_;
    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return Whether the connectedText field is set.
     */
    @java.lang.Override
    public boolean hasConnectedText() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return The connectedText.
     */
    @java.lang.Override
    public java.lang.String getConnectedText() {
      java.lang.Object ref = connectedText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          connectedText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string connected_text = 1 [default = "connected"];</code>
     * @return The bytes for connectedText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConnectedTextBytes() {
      java.lang.Object ref = connectedText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connectedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISCONNECTED_TEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object disconnectedText_;
    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return Whether the disconnectedText field is set.
     */
    @java.lang.Override
    public boolean hasDisconnectedText() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return The disconnectedText.
     */
    @java.lang.Override
    public java.lang.String getDisconnectedText() {
      java.lang.Object ref = disconnectedText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          disconnectedText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
     * @return The bytes for disconnectedText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisconnectedTextBytes() {
      java.lang.Object ref = disconnectedText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        disconnectedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOINED_TEXT_FIELD_NUMBER = 3;
    private volatile java.lang.Object joinedText_;
    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return Whether the joinedText field is set.
     */
    @java.lang.Override
    public boolean hasJoinedText() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return The joinedText.
     */
    @java.lang.Override
    public java.lang.String getJoinedText() {
      java.lang.Object ref = joinedText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          joinedText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
     * @return The bytes for joinedText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJoinedTextBytes() {
      java.lang.Object ref = joinedText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        joinedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESS_DENIED_TEXT_FIELD_NUMBER = 4;
    private volatile java.lang.Object accessDeniedText_;
    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return Whether the accessDeniedText field is set.
     */
    @java.lang.Override
    public boolean hasAccessDeniedText() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return The accessDeniedText.
     */
    @java.lang.Override
    public java.lang.String getAccessDeniedText() {
      java.lang.Object ref = accessDeniedText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          accessDeniedText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
     * @return The bytes for accessDeniedText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAccessDeniedTextBytes() {
      java.lang.Object ref = accessDeniedText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessDeniedText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_JOIN_TEXT_FIELD_NUMBER = 5;
    private volatile java.lang.Object requestJoinText_;
    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return Whether the requestJoinText field is set.
     */
    @java.lang.Override
    public boolean hasRequestJoinText() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return The requestJoinText.
     */
    @java.lang.Override
    public java.lang.String getRequestJoinText() {
      java.lang.Object ref = requestJoinText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestJoinText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string request_join_text = 5 [default = "Join request"];</code>
     * @return The bytes for requestJoinText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRequestJoinTextBytes() {
      java.lang.Object ref = requestJoinText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestJoinText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPROVE_JOIN_TEXT_FIELD_NUMBER = 6;
    private volatile java.lang.Object approveJoinText_;
    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return Whether the approveJoinText field is set.
     */
    @java.lang.Override
    public boolean hasApproveJoinText() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return The approveJoinText.
     */
    @java.lang.Override
    public java.lang.String getApproveJoinText() {
      java.lang.Object ref = approveJoinText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          approveJoinText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string approve_join_text = 6 [default = "yes"];</code>
     * @return The bytes for approveJoinText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getApproveJoinTextBytes() {
      java.lang.Object ref = approveJoinText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        approveJoinText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DENY_JOIN_TEXT_FIELD_NUMBER = 7;
    private volatile java.lang.Object denyJoinText_;
    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return Whether the denyJoinText field is set.
     */
    @java.lang.Override
    public boolean hasDenyJoinText() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return The denyJoinText.
     */
    @java.lang.Override
    public java.lang.String getDenyJoinText() {
      java.lang.Object ref = denyJoinText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          denyJoinText_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deny_join_text = 7 [default = "no"];</code>
     * @return The bytes for denyJoinText.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDenyJoinTextBytes() {
      java.lang.Object ref = denyJoinText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        denyJoinText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, connectedText_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, disconnectedText_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, joinedText_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accessDeniedText_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, requestJoinText_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, approveJoinText_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, denyJoinText_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, connectedText_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, disconnectedText_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, joinedText_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accessDeniedText_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, requestJoinText_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, approveJoinText_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, denyJoinText_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof system_messages.SystemMessagesOuterClass.SystemMessages)) {
        return super.equals(obj);
      }
      system_messages.SystemMessagesOuterClass.SystemMessages other = (system_messages.SystemMessagesOuterClass.SystemMessages) obj;

      if (hasConnectedText() != other.hasConnectedText()) return false;
      if (hasConnectedText()) {
        if (!getConnectedText()
            .equals(other.getConnectedText())) return false;
      }
      if (hasDisconnectedText() != other.hasDisconnectedText()) return false;
      if (hasDisconnectedText()) {
        if (!getDisconnectedText()
            .equals(other.getDisconnectedText())) return false;
      }
      if (hasJoinedText() != other.hasJoinedText()) return false;
      if (hasJoinedText()) {
        if (!getJoinedText()
            .equals(other.getJoinedText())) return false;
      }
      if (hasAccessDeniedText() != other.hasAccessDeniedText()) return false;
      if (hasAccessDeniedText()) {
        if (!getAccessDeniedText()
            .equals(other.getAccessDeniedText())) return false;
      }
      if (hasRequestJoinText() != other.hasRequestJoinText()) return false;
      if (hasRequestJoinText()) {
        if (!getRequestJoinText()
            .equals(other.getRequestJoinText())) return false;
      }
      if (hasApproveJoinText() != other.hasApproveJoinText()) return false;
      if (hasApproveJoinText()) {
        if (!getApproveJoinText()
            .equals(other.getApproveJoinText())) return false;
      }
      if (hasDenyJoinText() != other.hasDenyJoinText()) return false;
      if (hasDenyJoinText()) {
        if (!getDenyJoinText()
            .equals(other.getDenyJoinText())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasConnectedText()) {
        hash = (37 * hash) + CONNECTED_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getConnectedText().hashCode();
      }
      if (hasDisconnectedText()) {
        hash = (37 * hash) + DISCONNECTED_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getDisconnectedText().hashCode();
      }
      if (hasJoinedText()) {
        hash = (37 * hash) + JOINED_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getJoinedText().hashCode();
      }
      if (hasAccessDeniedText()) {
        hash = (37 * hash) + ACCESS_DENIED_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getAccessDeniedText().hashCode();
      }
      if (hasRequestJoinText()) {
        hash = (37 * hash) + REQUEST_JOIN_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getRequestJoinText().hashCode();
      }
      if (hasApproveJoinText()) {
        hash = (37 * hash) + APPROVE_JOIN_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getApproveJoinText().hashCode();
      }
      if (hasDenyJoinText()) {
        hash = (37 * hash) + DENY_JOIN_TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getDenyJoinText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static system_messages.SystemMessagesOuterClass.SystemMessages parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(system_messages.SystemMessagesOuterClass.SystemMessages prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code system_messages.SystemMessages}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:system_messages.SystemMessages)
        system_messages.SystemMessagesOuterClass.SystemMessagesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return system_messages.SystemMessagesOuterClass.internal_static_system_messages_SystemMessages_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return system_messages.SystemMessagesOuterClass.internal_static_system_messages_SystemMessages_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                system_messages.SystemMessagesOuterClass.SystemMessages.class, system_messages.SystemMessagesOuterClass.SystemMessages.Builder.class);
      }

      // Construct using system_messages.SystemMessagesOuterClass.SystemMessages.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        connectedText_ = "connected";
        bitField0_ = (bitField0_ & ~0x00000001);
        disconnectedText_ = "disconnected";
        bitField0_ = (bitField0_ & ~0x00000002);
        joinedText_ = "Joined group chat";
        bitField0_ = (bitField0_ & ~0x00000004);
        accessDeniedText_ = "Access denied!";
        bitField0_ = (bitField0_ & ~0x00000008);
        requestJoinText_ = "Join request";
        bitField0_ = (bitField0_ & ~0x00000010);
        approveJoinText_ = "yes";
        bitField0_ = (bitField0_ & ~0x00000020);
        denyJoinText_ = "no";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return system_messages.SystemMessagesOuterClass.internal_static_system_messages_SystemMessages_descriptor;
      }

      @java.lang.Override
      public system_messages.SystemMessagesOuterClass.SystemMessages getDefaultInstanceForType() {
        return system_messages.SystemMessagesOuterClass.SystemMessages.getDefaultInstance();
      }

      @java.lang.Override
      public system_messages.SystemMessagesOuterClass.SystemMessages build() {
        system_messages.SystemMessagesOuterClass.SystemMessages result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public system_messages.SystemMessagesOuterClass.SystemMessages buildPartial() {
        system_messages.SystemMessagesOuterClass.SystemMessages result = new system_messages.SystemMessagesOuterClass.SystemMessages(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.connectedText_ = connectedText_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.disconnectedText_ = disconnectedText_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.joinedText_ = joinedText_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.accessDeniedText_ = accessDeniedText_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          to_bitField0_ |= 0x00000010;
        }
        result.requestJoinText_ = requestJoinText_;
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.approveJoinText_ = approveJoinText_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          to_bitField0_ |= 0x00000040;
        }
        result.denyJoinText_ = denyJoinText_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof system_messages.SystemMessagesOuterClass.SystemMessages) {
          return mergeFrom((system_messages.SystemMessagesOuterClass.SystemMessages)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(system_messages.SystemMessagesOuterClass.SystemMessages other) {
        if (other == system_messages.SystemMessagesOuterClass.SystemMessages.getDefaultInstance()) return this;
        if (other.hasConnectedText()) {
          bitField0_ |= 0x00000001;
          connectedText_ = other.connectedText_;
          onChanged();
        }
        if (other.hasDisconnectedText()) {
          bitField0_ |= 0x00000002;
          disconnectedText_ = other.disconnectedText_;
          onChanged();
        }
        if (other.hasJoinedText()) {
          bitField0_ |= 0x00000004;
          joinedText_ = other.joinedText_;
          onChanged();
        }
        if (other.hasAccessDeniedText()) {
          bitField0_ |= 0x00000008;
          accessDeniedText_ = other.accessDeniedText_;
          onChanged();
        }
        if (other.hasRequestJoinText()) {
          bitField0_ |= 0x00000010;
          requestJoinText_ = other.requestJoinText_;
          onChanged();
        }
        if (other.hasApproveJoinText()) {
          bitField0_ |= 0x00000020;
          approveJoinText_ = other.approveJoinText_;
          onChanged();
        }
        if (other.hasDenyJoinText()) {
          bitField0_ |= 0x00000040;
          denyJoinText_ = other.denyJoinText_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        system_messages.SystemMessagesOuterClass.SystemMessages parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (system_messages.SystemMessagesOuterClass.SystemMessages) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object connectedText_ = "connected";
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @return Whether the connectedText field is set.
       */
      public boolean hasConnectedText() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @return The connectedText.
       */
      public java.lang.String getConnectedText() {
        java.lang.Object ref = connectedText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            connectedText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @return The bytes for connectedText.
       */
      public com.google.protobuf.ByteString
          getConnectedTextBytes() {
        java.lang.Object ref = connectedText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          connectedText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @param value The connectedText to set.
       * @return This builder for chaining.
       */
      public Builder setConnectedText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        connectedText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @return This builder for chaining.
       */
      public Builder clearConnectedText() {
        bitField0_ = (bitField0_ & ~0x00000001);
        connectedText_ = getDefaultInstance().getConnectedText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string connected_text = 1 [default = "connected"];</code>
       * @param value The bytes for connectedText to set.
       * @return This builder for chaining.
       */
      public Builder setConnectedTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        connectedText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object disconnectedText_ = "disconnected";
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @return Whether the disconnectedText field is set.
       */
      public boolean hasDisconnectedText() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @return The disconnectedText.
       */
      public java.lang.String getDisconnectedText() {
        java.lang.Object ref = disconnectedText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            disconnectedText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @return The bytes for disconnectedText.
       */
      public com.google.protobuf.ByteString
          getDisconnectedTextBytes() {
        java.lang.Object ref = disconnectedText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          disconnectedText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @param value The disconnectedText to set.
       * @return This builder for chaining.
       */
      public Builder setDisconnectedText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        disconnectedText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDisconnectedText() {
        bitField0_ = (bitField0_ & ~0x00000002);
        disconnectedText_ = getDefaultInstance().getDisconnectedText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string disconnected_text = 2 [default = "disconnected"];</code>
       * @param value The bytes for disconnectedText to set.
       * @return This builder for chaining.
       */
      public Builder setDisconnectedTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        disconnectedText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object joinedText_ = "Joined group chat";
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @return Whether the joinedText field is set.
       */
      public boolean hasJoinedText() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @return The joinedText.
       */
      public java.lang.String getJoinedText() {
        java.lang.Object ref = joinedText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            joinedText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @return The bytes for joinedText.
       */
      public com.google.protobuf.ByteString
          getJoinedTextBytes() {
        java.lang.Object ref = joinedText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          joinedText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @param value The joinedText to set.
       * @return This builder for chaining.
       */
      public Builder setJoinedText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        joinedText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @return This builder for chaining.
       */
      public Builder clearJoinedText() {
        bitField0_ = (bitField0_ & ~0x00000004);
        joinedText_ = getDefaultInstance().getJoinedText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string joined_text = 3 [default = "Joined group chat"];</code>
       * @param value The bytes for joinedText to set.
       * @return This builder for chaining.
       */
      public Builder setJoinedTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        joinedText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessDeniedText_ = "Access denied!";
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @return Whether the accessDeniedText field is set.
       */
      public boolean hasAccessDeniedText() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @return The accessDeniedText.
       */
      public java.lang.String getAccessDeniedText() {
        java.lang.Object ref = accessDeniedText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            accessDeniedText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @return The bytes for accessDeniedText.
       */
      public com.google.protobuf.ByteString
          getAccessDeniedTextBytes() {
        java.lang.Object ref = accessDeniedText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessDeniedText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @param value The accessDeniedText to set.
       * @return This builder for chaining.
       */
      public Builder setAccessDeniedText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accessDeniedText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @return This builder for chaining.
       */
      public Builder clearAccessDeniedText() {
        bitField0_ = (bitField0_ & ~0x00000008);
        accessDeniedText_ = getDefaultInstance().getAccessDeniedText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string access_denied_text = 4 [default = "Access denied!"];</code>
       * @param value The bytes for accessDeniedText to set.
       * @return This builder for chaining.
       */
      public Builder setAccessDeniedTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        accessDeniedText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestJoinText_ = "Join request";
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @return Whether the requestJoinText field is set.
       */
      public boolean hasRequestJoinText() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @return The requestJoinText.
       */
      public java.lang.String getRequestJoinText() {
        java.lang.Object ref = requestJoinText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestJoinText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @return The bytes for requestJoinText.
       */
      public com.google.protobuf.ByteString
          getRequestJoinTextBytes() {
        java.lang.Object ref = requestJoinText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestJoinText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @param value The requestJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setRequestJoinText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestJoinText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @return This builder for chaining.
       */
      public Builder clearRequestJoinText() {
        bitField0_ = (bitField0_ & ~0x00000010);
        requestJoinText_ = getDefaultInstance().getRequestJoinText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string request_join_text = 5 [default = "Join request"];</code>
       * @param value The bytes for requestJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setRequestJoinTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        requestJoinText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object approveJoinText_ = "yes";
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @return Whether the approveJoinText field is set.
       */
      public boolean hasApproveJoinText() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @return The approveJoinText.
       */
      public java.lang.String getApproveJoinText() {
        java.lang.Object ref = approveJoinText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            approveJoinText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @return The bytes for approveJoinText.
       */
      public com.google.protobuf.ByteString
          getApproveJoinTextBytes() {
        java.lang.Object ref = approveJoinText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          approveJoinText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @param value The approveJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setApproveJoinText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        approveJoinText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @return This builder for chaining.
       */
      public Builder clearApproveJoinText() {
        bitField0_ = (bitField0_ & ~0x00000020);
        approveJoinText_ = getDefaultInstance().getApproveJoinText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string approve_join_text = 6 [default = "yes"];</code>
       * @param value The bytes for approveJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setApproveJoinTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        approveJoinText_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object denyJoinText_ = "no";
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @return Whether the denyJoinText field is set.
       */
      public boolean hasDenyJoinText() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @return The denyJoinText.
       */
      public java.lang.String getDenyJoinText() {
        java.lang.Object ref = denyJoinText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            denyJoinText_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @return The bytes for denyJoinText.
       */
      public com.google.protobuf.ByteString
          getDenyJoinTextBytes() {
        java.lang.Object ref = denyJoinText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          denyJoinText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @param value The denyJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setDenyJoinText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        denyJoinText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @return This builder for chaining.
       */
      public Builder clearDenyJoinText() {
        bitField0_ = (bitField0_ & ~0x00000040);
        denyJoinText_ = getDefaultInstance().getDenyJoinText();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deny_join_text = 7 [default = "no"];</code>
       * @param value The bytes for denyJoinText to set.
       * @return This builder for chaining.
       */
      public Builder setDenyJoinTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        denyJoinText_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:system_messages.SystemMessages)
    }

    // @@protoc_insertion_point(class_scope:system_messages.SystemMessages)
    private static final system_messages.SystemMessagesOuterClass.SystemMessages DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new system_messages.SystemMessagesOuterClass.SystemMessages();
    }

    public static system_messages.SystemMessagesOuterClass.SystemMessages getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SystemMessages>
        PARSER = new com.google.protobuf.AbstractParser<SystemMessages>() {
      @java.lang.Override
      public SystemMessages parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SystemMessages(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SystemMessages> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SystemMessages> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public system_messages.SystemMessagesOuterClass.SystemMessages getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_system_messages_SystemMessages_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_system_messages_SystemMessages_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025system_messages.proto\022\017system_messages" +
      "\"\225\002\n\016SystemMessages\022!\n\016connected_text\030\001 " +
      "\001(\t:\tconnected\022\'\n\021disconnected_text\030\002 \001(" +
      "\t:\014disconnected\022&\n\013joined_text\030\003 \001(\t:\021Jo" +
      "ined group chat\022*\n\022access_denied_text\030\004 " +
      "\001(\t:\016Access denied!\022\'\n\021request_join_text" +
      "\030\005 \001(\t:\014Join request\022\036\n\021approve_join_tex" +
      "t\030\006 \001(\t:\003yes\022\032\n\016deny_join_text\030\007 \001(\t:\002no"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_system_messages_SystemMessages_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_system_messages_SystemMessages_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_system_messages_SystemMessages_descriptor,
        new java.lang.String[] { "ConnectedText", "DisconnectedText", "JoinedText", "AccessDeniedText", "RequestJoinText", "ApproveJoinText", "DenyJoinText", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
